networks:
  app-tier:
    driver: bridge

services:
  postgresql:
    container_name: postgres
    image: 'bitnami/postgresql:15.3.0'
    networks:
      - app-tier
    environment:
      - POSTGRESQL_DATABASE=dmg
      - POSTGRESQL_USERNAME=gosier
      - POSTGRESQL_PASSWORD=gosier
    ports:
      - "5432:5432"