# Docker bridge network for our services
networks:
  dmg-net:
    driver: bridge

services:
  # Reverse proxy and load balancing service with traefik
  traefik:
    container_name: traefik
    image: traefik:v3.0
    command:
      - --api.insecure=true                       
      - --providers.docker                       
      - --providers.docker.exposedbydefault=false 
      - --entrypoints.web.address=:80
    networks:
      - dmg-net
    ports:
      - 80:80
      - 8080:8080
    expose:
      - 80
    volumes:
      - ${DOCKER_SOCKET_PATH_LINUX}:/var/run/docker.sock

  # Access control middleware
  access-control:
    container_name: ${MIDDLEWARE_AUTH_HOST}
    build: ./Middleware
    image: access-control:1.0
    environment:
      - MIDDLEWARE_AUTH_PORT=${MIDDLEWARE_AUTH_PORT}
      - POSTGRE_HOST=${POSTGRE_HOST}
      - POSTGRE_DATABASE=${POSTGRE_DATABASE}
      - POSTGRE_USERNAME=${POSTGRE_USERNAME}
      - POSTGRE_PASSWORD=${POSTGRE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.middlewares.access-control.forwardauth.address=http://${MIDDLEWARE_AUTH_HOST}:${MIDDLEWARE_AUTH_PORT}
      - traefik.http.middlewares.access-control.forwardauth.authResponseHeaders=X-Forwarded-AccountID
      - traefik.http.services.access-control.loadbalancer.server.port=${MIDDLEWARE_AUTH_PORT}
    networks:
      - dmg-net
    expose:
      - ${MIDDLEWARE_AUTH_PORT}

  # Auth microservice
  auth:
    container_name: ${MICROSERVICE_AUTH_HOST}
    build: ./apis/auth
    image: auth:1.0
    depends_on:
      - postgres
    environment:
      - MICROSERVICE_AUTH_PORT=${MICROSERVICE_AUTH_PORT}
      - POSTGRE_HOST=${POSTGRE_HOST}
      - POSTGRE_DATABASE=${POSTGRE_DATABASE}
      - POSTGRE_USERNAME=${POSTGRE_USERNAME}
      - POSTGRE_PASSWORD=${POSTGRE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.auth.rule=PathPrefix(`/register`) || PathPrefix(`/login`)
      - traefik.http.routers.auth.entrypoints=web
      - traefik.http.services.auth.loadbalancer.server.port=${MICROSERVICE_AUTH_PORT}
    networks:
      - dmg-net
    expose:
      - ${MICROSERVICE_AUTH_PORT}

  # Account microservice
  account:
    container_name: ${MICROSERVICE_ACCOUNT_HOST}
    build: ./apis/account
    image: account:1.0
    depends_on:
      - postgres
    environment:
      - MICROSERVICE_ACCOUNT_PORT=${MICROSERVICE_ACCOUNT_PORT}
      - POSTGRE_HOST=${POSTGRE_HOST}
      - POSTGRE_DATABASE=${POSTGRE_DATABASE}
      - POSTGRE_USERNAME=${POSTGRE_USERNAME}
      - POSTGRE_PASSWORD=${POSTGRE_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    labels:
      - traefik.enable=true
      - traefik.http.routers.account.rule=PathPrefix(`/account`)
      - traefik.http.routers.account.entrypoints=web
      - traefik.http.routers.account.middlewares=access-control
      - traefik.http.services.account.loadbalancer.server.port=${MICROSERVICE_ACCOUNT_PORT}
    networks:
      - dmg-net
    expose:
      - ${MICROSERVICE_ACCOUNT_PORT}
    ports:
      - ${MICROSERVICE_ACCOUNT_PORT}:${MICROSERVICE_ACCOUNT_PORT}
  
  # Sponsor microservice
  sponsor:
    container_name: ${MICROSERVICE_SPONSOR_HOST}
    build: ./apis/sponsor
    image: sponsor:1.0
    depends_on:
      - postgres
    environment:
      - MICROSERVICE_SPONSOR_PORT=${MICROSERVICE_SPONSOR_PORT}
      - POSTGRE_HOST=${POSTGRE_HOST}
      - POSTGRE_DATABASE=${POSTGRE_DATABASE}
      - POSTGRE_USERNAME=${POSTGRE_USERNAME}
      - POSTGRE_PASSWORD=${POSTGRE_PASSWORD}
    labels:
      - traefik.enable=true
      - traefik.http.routers.sponsor.rule=PathPrefix(`/sponsor`)
      - traefik.http.routers.sponsor.entrypoints=web
      - traefik.http.routers.sponsor.middlewares=access-control
      - traefik.http.services.sponsor.loadbalancer.server.port=${MICROSERVICE_SPONSOR_PORT}
    networks:
      - dmg-net
    expose:
      - ${MICROSERVICE_SPONSOR_PORT}
  
  # Address microservice
  address:
    container_name: ${MICROSERVICE_ADDRESS_HOST}
    build: ./apis/address
    image: address:1.0
    depends_on:
      - postgres
    environment:
      - MICROSERVICE_ADDRESS_PORT=${MICROSERVICE_ADDRESS_PORT}
      - MONGODB_URL=${MONGODB_URL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.address.rule=PathPrefix(`/address`)
      - traefik.http.routers.address.entrypoints=web
      - traefik.http.routers.address.middlewares=access-control
      - traefik.http.services.address.loadbalancer.server.port=${MICROSERVICE_ADDRESS_PORT}
    networks:
      - dmg-net
    expose:
      - ${MICROSERVICE_ADDRESS_PORT}
    ports:
      - ${MICROSERVICE_ADDRESS_PORT}:${MICROSERVICE_ADDRESS_PORT}

  # Order microservice
  order:
    container_name: ${MICROSERVICE_ORDER_HOST}
    build: ./apis/order
    image: order:1.0
    depends_on:
      - postgres
    environment:
      - MICROSERVICE_ORDER_PORT=${MICROSERVICE_ORDER_PORT}
      - MONGODB_URL=${MONGODB_URL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.order.rule=PathPrefix(`/order`)
      - traefik.http.routers.order.entrypoints=web
      - traefik.http.routers.order.middlewares=access-control
      - traefik.http.services.order.loadbalancer.server.port=${MICROSERVICE_ORDER_PORT}
    networks:
      - dmg-net
    expose:
      - ${MICROSERVICE_ORDER_PORT}
    ports:
      - ${MICROSERVICE_ORDER_PORT}:${MICROSERVICE_ORDER_PORT}

  # Restaurant microservice
  restaurant:
    container_name: ${MICROSERVICE_RESTAURANT_HOST}
    build: ./apis/restaurant
    image: restaurant:1.0
    depends_on:
      - postgres
    environment:
      - MICROSERVICE_RESTAURANT_PORT=${MICROSERVICE_RESTAURANT_PORT}
      - MONGODB_URL=${MONGODB_URL}      
    labels:
      - traefik.enable=true
      - traefik.http.routers.restaurant.rule=PathPrefix(`/restaurant`)
      - traefik.http.routers.restaurant.entrypoints=web
      - traefik.http.routers.restaurant.middlewares=access-control
      - traefik.http.services.restaurant.loadbalancer.server.port=${MICROSERVICE_RESTAURANT_PORT}
    networks:
      - dmg-net
    expose:
      - ${MICROSERVICE_RESTAURANT_PORT}
    ports:
      - ${MICROSERVICE_RESTAURANT_PORT}:${MICROSERVICE_RESTAURANT_PORT}

  # Stats microservice
  stats:
    container_name: ${MICROSERVICE_STATS_HOST}
    build: ./apis/stats
    image: stats:1.0
    depends_on:
      - postgres
    environment:
      - MICROSERVICE_STATS_PORT=${MICROSERVICE_STATS_PORT}
      - MONGODB_URL=${MONGODB_URL}
    labels:
      - traefik.enable=true
      - traefik.http.routers.stats.rule=PathPrefix(`/stats`)
      - traefik.http.routers.stats.entrypoints=web
      - traefik.http.routers.stats.middlewares=access-control
      - traefik.http.services.stats.loadbalancer.server.port=${MICROSERVICE_STATS_PORT}
    networks:
      - dmg-net
    expose:
      - ${MICROSERVICE_STATS_PORT}
    ports:
      - ${MICROSERVICE_STATS_PORT}:${MICROSERVICE_STATS_PORT}

  # PostgreSQL database
  postgres:
    container_name: ${POSTGRE_HOST}
    image: bitnami/postgresql:15.3.0
    networks:
      - dmg-net
    environment:
      - POSTGRESQL_DATABASE=${POSTGRE_DATABASE}
      - POSTGRESQL_USERNAME=${POSTGRE_USERNAME}
      - POSTGRESQL_PASSWORD=${POSTGRE_PASSWORD}
    expose:
      - 5432
    ports:
      - 5432:5432
    # volumes:
    #   - ${POSTGRE_DATA}:/bitnami/postgresql
    



