openapi: 3.0.0
info:
  title: Order API
  description: API for managing orders
  version: 1.0.0
servers:
  - url: http://localhost:3012
paths:
  /orders:
    post:
      summary: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderInput'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
    get:
      summary: Get an order by ID
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order found successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
    put:
      summary: Update an order by ID
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderInput'
      responses:
        '200':
          description: Order updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found
    delete:
      summary: Delete an order by ID
      parameters:
        - in: path
          name: orderId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order deleted successfully
        '404':
          description: Order not found
components:
  schemas:
    Order:
      type: object
      properties:
        _id:
          type: string
        id_user:
          type: string
        id_restaurant:
          type: string
        price:
          type: number
        number:
          type: string
        payment:
          type: string
          enum: [paid, unpaid]
        status:
          type: string
          enum: [ordering, accepted_order, accepted_delivery, delivered, refused_order, refused_delivery]
        date:
          type: object
          properties:
            start:
              type: string
              format: date-time
            end:
              type: string
              format: date-time
          required:
            - start
        address:
          type: string
        deliverer:
          type: string
        menus:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              quantity:
                type: number
        items:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              quantity:
                type: number
    OrderInput:
      type: object
      properties:
        id_user:
          type: string
        id_restaurant:
          type: string
        price:
          type: number
        number:
          type: string
        payment:
          type: string
          enum: [paid, unpaid]
        status:
          type: string
          enum: [ordering, accepted_order, accepted_delivery, delivered, refused_order, refused_delivery]
        date:
          type: object
          properties:
            start:
              type: string
              format: date-time
            end:
              type: string
              format: date-time
          required:
            - start
        address:
          type: string
        deliverer:
          type: string
        menus:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              quantity:
                type: number
        items:
          type: array
          items:
            type: object
            properties:
              _id:
                type: string
              quantity:
                type: number
