openapi: 3.0.0
info:
  version: '1.0.0'
  title: 'Address API'
  description: 'API for managing addresses'
servers:
  - url: http://localhost:3004
paths:
  /address/{addressId}:
    get:
      summary: 'Get an address by ID'
      description: 'Retrieve the details of an address by its ID'
      parameters:
        - in: 'path'
          name: 'addressId'
          required: true
          type: 'string'
      responses:
        '200':
          description: 'Address retrieved successfully'
        '404':
          description: 'Address not found'
        '500':
          description: 'Error while retrieving the address'
    put:
      summary: 'Update an address'
      description: 'Update the details of an address by its ID'
      parameters:
        - in: 'path'
          name: 'addressId'
          required: true
          type: 'string'
        - in: 'body'
          name: 'body'
          description: 'The updated details of the address'
          required: true
          schema:
            $ref: '#/definitions/Address'
      responses:
        '200':
          description: 'Address updated successfully'
        '404':
          description: 'Address not found'
        '500':
          description: 'Error while updating the address'
    delete:
      summary: 'Delete an address'
      description: 'Delete an address by its ID'
      parameters:
        - in: 'path'
          name: 'addressId'
          required: true
          type: 'string'
      responses:
        '200':
          description: 'Address deleted successfully'
        '404':
          description: 'Address not found'
        '500':
          description: 'Error while deleting the address'
  /address:
    post:
      summary: 'Create a new address'
      description: 'Create a new address with the given details'
      parameters:
        - in: 'body'
          name: 'body'
          description: 'The details of the address to be created'
          required: true
          schema:
            $ref: '#/definitions/Address'
      responses:
        '201':
          description: 'Address created successfully'
        '400':
          description: 'Could not find GPS coordinates for this address'
        '500':
          description: 'Error while creating a new address'
  /address-by-credentials/{id_credentials}:
    get:
      summary: 'Get an address by credentials ID'
      description: 'Retrieve the details of an address by its credentials ID'
      parameters:
        - in: 'path'
          name: 'id_credentials'
          required: true
          type: 'string'
      responses:
        '200':
          description: 'Address retrieved successfully'
        '404':
          description: 'Address not found'
        '500':
          description: 'Error while getting the address'
definitions:
  Address:
    type: 'object'
    properties:
      id_credentials:
        type: 'string'
      type:
        type: 'string'
        enum: ['restaurant', 'client']
      line_1:
        type: 'string'
      line_2:
        type: 'string'
      city:
        type: 'string'
      country:
        type: 'string'
      postcode:
        type: 'string'
      coordinates:
        type: 'array'
        items:
          type: 'number'