openapi: 3.0.0
info:
  title: DansMonGosier
  description: Description de mon API
  version: 1.0.0
servers:
  - url: http://localhost:3010
paths:
  /items:
    post:
      summary: Créer un nouvel item
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemInput'
      responses:
        '201':
          description: Item créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
    get:
      summary: Récupérer la liste des items
      responses:
        '200':
          description: Succès
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
  /items/{itemId}:
    get:
      summary: Récupérer un item par son ID
      parameters:
        - in: path
          name: itemId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item trouvé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Item non trouvé
    put:
      summary: Mettre à jour un item par son ID
      parameters:
        - in: path
          name: itemId
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ItemInput'
      responses:
        '200':
          description: Item mis à jour avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '404':
          description: Item non trouvé
    delete:
      summary: Supprimer un item par son ID
      parameters:
        - in: path
          name: itemId
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Item supprimé avec succès
        '404':
          description: Item non trouvé
components:
  schemas:
    Item:
      type: object
      properties:
        _id:
          type: string
        id_restaurant:
          type: string
        label:
          type: string
        description:
          type: string
        photo:
          type: string
        price:
          type: number
        type:
          type: string
          enum: [plat, boisson, sauce, accompagnement]
    ItemInput:
      type: object
      properties:
        id_restaurant:
          type: string
        label:
          type: string
        description:
          type: string
        photo:
          type: string
        price:
          type: number
        type:
          type: string
          enum: [plat, boisson, sauce, accompagnement]
